[env]
PROFILE = { value = "release", condition = { env_not_set = ["PROFILE"] } }
PROFILE_DIR = { value = "release", condition = { env_not_set = [
  "PROFILE_DIR",
] } }
CROSS_CC = "x86_64-linux-gnu-gcc"
CROSS_CXX = "x86_64-linux-gnu-g++"
CROSS_CFLAGS = ""
TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/x86_64"
LIBPNG_ARCH = "x86_64"
LIBPNG_OPTIMIZATIONS = "yes"
FEATURE = "x86_64"
LIBAFL_LOCATION = "/home/cosmix/thesis"
#LIBAFL_DEBUG_OUTPUT = "1"
#CUSTOM_QEMU_DIR= "~/qemu-libafl-bridge"

[env.vm_server]
CROSS_CC = "x86_64-linux-gnu-gcc"
CROSS_CXX = "x86_64-linux-gnu-g++"
CROSS_CFLAGS = ""
TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/x86_64"
LIBPNG_ARCH = "x86_64"
LIBPNG_OPTIMIZATIONS = "yes"
FEATURE = "x86_64"
LIBAFL_LOCATION = "/home/banica"

[env.arm]
CROSS_CC = "arm-linux-gnueabi-gcc"
CROSS_CXX = "arm-linux-gnueabi-g++"
CROSS_CFLAGS = ""
TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/arm"
LIBPNG_ARCH = "arm"
LIBPNG_OPTIMIZATIONS = "yes"
FEATURE = "arm"

[env.aarch64]
CROSS_CC = "aarch64-linux-gnu-gcc"
CROSS_CXX = "aarch64-linux-gnu-g++"
CROSS_CFLAGS = ""
TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/aarch64"
LIBPNG_ARCH = "aarch64"
LIBPNG_OPTIMIZATIONS = "yes"
FEATURE = "aarch64"

[env.x86_64]
CROSS_CC = "x86_64-linux-gnu-gcc"
CROSS_CXX = "x86_64-linux-gnu-g++"
CROSS_CFLAGS = ""
TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/x86_64"
LIBPNG_ARCH = "x86_64"
LIBPNG_OPTIMIZATIONS = "yes"
FEATURE = "x86_64"
LIBAFL_LOCATION = "/home/cosmix/thesis"

[env.i386]
CROSS_CC = "x86_64-linux-gnu-gcc"
CROSS_CXX = "x86_64-linux-gnu-g++"
CROSS_CFLAGS = "-m32"
TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/i386"
LIBPNG_ARCH = "i386"
LIBPNG_OPTIMIZATIONS = "yes"
FEATURE = "i386"

[env.mips]
CROSS_CC = "mipsel-linux-gnu-gcc"
CROSS_CXX = "mipsel-linux-gnu-g++"
CROSS_CFLAGS = ""
TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/mips"
LIBPNG_ARCH = "mips"
LIBPNG_OPTIMIZATIONS = "yes"
FEATURE = "mips"

[env.ppc]
CROSS_CC = "powerpc-linux-gnu-gcc"
CROSS_CXX = "powerpc-linux-gnu-g++"
CROSS_CFLAGS = ""
TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/ppc"
LIBPNG_ARCH = "ppc"
LIBPNG_OPTIMIZATIONS = "no"
FEATURE = "ppc"

[tasks.unsupported]
script_runner = "@shell"
script = '''
echo "Qemu fuzzer not supported on windows/mac"
'''

[tasks.target_dir]
condition = { files_not_exist = ["${CARGO_MAKE_CRATE_TARGET_DIRECTORY}"] }
script_runner = "@shell"
script = '''
mkdir ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}
'''

[tasks.deps_dir]
dependencies = ["target_dir"]
condition = { files_not_exist = ["${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/"] }
script_runner = "@shell"
script = '''
mkdir ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/
'''

[tasks.arch_target_dir]
dependencies = ["target_dir"]
condition = { files_not_exist = ["${TARGET_DIR}"] }
script_runner = "@shell"
script = '''
mkdir ${TARGET_DIR}
'''

[tasks.zlib]
linux_alias = "zlib_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.zlib_unix_wget]
dependencies = ["deps_dir"]
condition = { files_not_exist = [
  "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/zlib-1.2.13",
] }
script_runner = "@shell"
# NOTE: There's no specific reason we're using an old version of zlib,
# but newer versions get moved to fossils/ after a while.
script = '''
wget \
    -O "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/zlib-1.2.13.tar.gz" \
    https://zlib.net/fossils/zlib-1.2.13.tar.gz

tar \
    zxvf ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/zlib-1.2.13.tar.gz \
    -C ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/
'''

[tasks.zlib_unix]
dependencies = ["arch_target_dir", "zlib_unix_wget"]
condition = { files_not_exist = ["${TARGET_DIR}/build-zlib/libz.a"] }
script_runner = "@shell"
script = '''
rm -rf ${TARGET_DIR}/build-zlib/

mkdir ${TARGET_DIR}/build-zlib/

cd ${TARGET_DIR}/build-zlib/ && \
    CC=$CROSS_CC \
    CFLAGS=${CROSS_CFLAGS} \
    ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/zlib-1.2.13/configure \
        --prefix=./zlib

make install
'''

[tasks.libpng]
linux_alias = "libpng_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.libpng_unix_wget]
dependencies = ["deps_dir"]
condition = { files_not_exist = [
  "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/libpng-1.6.37",
] }
script_runner = "@shell"
script = '''
wget \
    -O "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/v1.6.37.tar.gz" \
    https://github.com/glennrp/libpng/archive/refs/tags/v1.6.37.tar.gz

tar \
    -xvf "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/v1.6.37.tar.gz" \
    -C ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/
'''

[tasks.libpng_unix]
dependencies = ["arch_target_dir", "zlib", "libpng_unix_wget"]
condition = { files_not_exist = ["${TARGET_DIR}/build-png/.libs/libpng16.a"] }
script_runner = "@shell"
script = '''
rm -rf ${TARGET_DIR}/build-png/

mkdir ${TARGET_DIR}/build-png/

cd ${TARGET_DIR}/build-png/ && \
    CC=$CROSS_CC \
    CFLAGS="${CROSS_CFLAGS}" \
    CPPFLAGS="-I${TARGET_DIR}/build-zlib/zlib/include" \
    LDFLAGS=-L"${TARGET_DIR}/build-zlib/zlib/lib" \
    ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/libpng-1.6.37/configure \
        --enable-shared=no \
        --with-pic=yes \
        --enable-hardware-optimizations=${LIBPNG_OPTIMIZATIONS} \
        --host=${LIBPNG_ARCH} \

make
'''

[tasks.build]
linux_alias = "build_unix"
mac_alias = "build_unix"
windows_alias = "unsupported"

[tasks.build_unix]
command = "cargo"
args = [
  "build",
  "--profile",
  "${PROFILE}",
  "--features",
  "${FEATURE}",
  "--target-dir",
  "${TARGET_DIR}",
]

[tasks.fuzzer]
dependencies = ["build"]
script_runner = "@shell"
script = '''
rm -f ${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}
mv ${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher ${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}
'''

[tasks.harness]
linux_alias = "harness_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.harness_unix]
script_runner = "@shell"
script = '''
${CROSS_CXX} \
    ./harness.cc \
    $CROSS_CFLAGS \
    "${TARGET_DIR}/build-png/.libs/libpng16.a" \
	"${TARGET_DIR}/build-zlib/libz.a" \
    -I"${TARGET_DIR}/build-png" \
    -I"${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/deps/libpng-1.6.37" \
	-I"${TARGET_DIR}/build-zlib/zlib/include" \
	-L"${TARGET_DIR}/build-zlib/zlib/lib" \
    -o"${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}" \
    -lm
'''
dependencies = ["libpng"]

[tasks.run]
linux_alias = "run_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.run_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}"
args = [
  "--input",
  "./corpus",
  "--output",
  "${TARGET_DIR}/output/",
  "--log",
  "${TARGET_DIR}/output/log.txt",
  "--cores",
  "0-7",
  "--asan-cores",
  "0-3",
  "--cmplog-cores",
  "2-5",
  "--iterations",
  "1000000",
  "--tui",
  "--",
  "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}",
]
dependencies = ["harness", "fuzzer"]

[tasks.test_harness]
linux_alias = "test_harness_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.test_harness_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-1"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/test_harness_corpus",
  "--output",
  "${TARGET_DIR}/output/test_harness/",
  "--log",
  "${TARGET_DIR}/output/test_harness/log.txt",
  "--cores",
  "0",
  "--asan-cores",
  "0",
  "--port",
  "1340",
  # "--verbose",
  "--duration",
  "36000",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/test_harness",
]
dependencies = ["harness", "fuzzer"]

[tasks.normal_expat]
linux_alias = "normal_expat_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.normal_expat_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-4"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libxml2/corpus/libxml2_xml_read_memory_fuzzer",
  "--output",
  "${TARGET_DIR}/output/normal_expat/",
  "--log",
  "${TARGET_DIR}/output/normal_expat/log.txt",
  "--cores",
  "4",
  "--port",
  "1344",
  # "--iterations",
  # "2000",
  "--verbose",
  "--duration",
  "36000",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/libexpat/expat/fuzz_src/expat_fuzzer",
]
dependencies = ["harness", "fuzzer"]

[tasks.asan_expat]
linux_alias = "asan_expat_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.asan_expat_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-5"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libxml2/corpus/libxml2_xml_read_memory_fuzzer",
  "--output",
  "${TARGET_DIR}/output/asan_expat/",
  "--log",
  "${TARGET_DIR}/output/asan_expat/log.txt",
  "--cores",
  "5",
  "--asan-cores",
  "5",
  "--port",
  "1345",
  # "--iterations",
  # "2000",
  "--verbose",
  "--duration",
  "36000",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/libexpat/expat/fuzz_src/expat_fuzzer",
]
dependencies = ["harness", "fuzzer"]

##
##
##
# Ratio test campaigns; all dynamic-san; all 24 hours; each on different 1 core and port; all libpng
# Half with "--use_blocks" and half without; all with "--ratio_start 0"; each with increasing "--dynamic_sanitizer_ratio", from 0 to 100, in steps of 10
# Name them: "ratio_test_libpng_0", "ratio_test_libpng_10", ..., "ratio_test_libpng_100", "block_test_libpng_0", "block_test_libpng_10", ..., "block_test_libpng_100"
##
##
##
[tasks.ratio_test_libpng_0]
linux_alias = "ratio_test_libpng_0_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ratio_test_libpng_0_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-16"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/ratio_test_libpng_0/", "--log", "${TARGET_DIR}/output/ratio_test_libpng_0/log.txt", "--cores", "15", "--asan-cores", "15", "--port", "1352", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "1", "--ratio_start", "0", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.ratio_test_libpng_10]
linux_alias = "ratio_test_libpng_10_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ratio_test_libpng_10_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-17"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/ratio_test_libpng_10/", "--log", "${TARGET_DIR}/output/ratio_test_libpng_10/log.txt", "--cores", "16", "--asan-cores", "16", "--port", "1353", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "10", "--ratio_start", "0", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.ratio_test_libpng_20]
linux_alias = "ratio_test_libpng_20_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ratio_test_libpng_20_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-18"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/ratio_test_libpng_20/", "--log", "${TARGET_DIR}/output/ratio_test_libpng_20/log.txt", "--cores", "17", "--asan-cores", "17", "--port", "1354", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "20", "--ratio_start", "0", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.ratio_test_libpng_30]
linux_alias = "ratio_test_libpng_30_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ratio_test_libpng_30_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-19"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/ratio_test_libpng_30/", "--log", "${TARGET_DIR}/output/ratio_test_libpng_30/log.txt", "--cores", "18", "--asan-cores", "18", "--port", "1355", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "30", "--ratio_start", "0", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.ratio_test_libpng_40]
linux_alias = "ratio_test_libpng_40_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ratio_test_libpng_40_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-20"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/ratio_test_libpng_40/", "--log", "${TARGET_DIR}/output/ratio_test_libpng_40/log.txt", "--cores", "19", "--asan-cores", "19", "--port", "1356", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "40", "--ratio_start", "0", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.ratio_test_libpng_50]
linux_alias = "ratio_test_libpng_50_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ratio_test_libpng_50_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-21"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/ratio_test_libpng_50/", "--log", "${TARGET_DIR}/output/ratio_test_libpng_50/log.txt", "--cores", "20", "--asan-cores", "20", "--port", "1357", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "50", "--ratio_start", "0", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.ratio_test_libpng_60]
linux_alias = "ratio_test_libpng_60_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ratio_test_libpng_60_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-22"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/ratio_test_libpng_60/", "--log", "${TARGET_DIR}/output/ratio_test_libpng_60/log.txt", "--cores", "21", "--asan-cores", "21", "--port", "1358", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "60", "--ratio_start", "0", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.ratio_test_libpng_70]
linux_alias = "ratio_test_libpng_70_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ratio_test_libpng_70_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-23"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/ratio_test_libpng_70/", "--log", "${TARGET_DIR}/output/ratio_test_libpng_70/log.txt", "--cores", "22", "--asan-cores", "22", "--port", "1359", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "70", "--ratio_start", "0", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.ratio_test_libpng_80]
linux_alias = "ratio_test_libpng_80_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ratio_test_libpng_80_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-24"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/ratio_test_libpng_80/", "--log", "${TARGET_DIR}/output/ratio_test_libpng_80/log.txt", "--cores", "23", "--asan-cores", "23", "--port", "1360", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "80", "--ratio_start", "0", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.ratio_test_libpng_90]
linux_alias = "ratio_test_libpng_90_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ratio_test_libpng_90_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-25"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/ratio_test_libpng_90/", "--log", "${TARGET_DIR}/output/ratio_test_libpng_90/log.txt", "--cores", "24", "--asan-cores", "24", "--port", "1361", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "90", "--ratio_start", "0", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.ratio_test_libpng_100]
linux_alias = "ratio_test_libpng_100_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ratio_test_libpng_100_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-26"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/ratio_test_libpng_100/", "--log", "${TARGET_DIR}/output/ratio_test_libpng_100/log.txt", "--cores", "25", "--asan-cores", "25", "--port", "1362", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "100", "--ratio_start", "0", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.block_test_libpng_0]
linux_alias = "block_test_libpng_0_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.block_test_libpng_0_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-27"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/block_test_libpng_0/", "--log", "${TARGET_DIR}/output/block_test_libpng_0/log.txt", "--cores", "26", "--asan-cores", "26", "--port", "1363", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "1", "--ratio_start", "0", "--use_blocks", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.block_test_libpng_10]
linux_alias = "block_test_libpng_10_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.block_test_libpng_10_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-28"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/block_test_libpng_10/", "--log", "${TARGET_DIR}/output/block_test_libpng_10/log.txt", "--cores", "27", "--asan-cores", "27", "--port", "1364", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "10", "--ratio_start", "0", "--use_blocks", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.block_test_libpng_20]
linux_alias = "block_test_libpng_20_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.block_test_libpng_20_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-29"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/block_test_libpng_20/", "--log", "${TARGET_DIR}/output/block_test_libpng_20/log.txt", "--cores", "28", "--asan-cores", "28", "--port", "1365", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "20", "--ratio_start", "0", "--use_blocks", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.block_test_libpng_30]
linux_alias = "block_test_libpng_30_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.block_test_libpng_30_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-30"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/block_test_libpng_30/", "--log", "${TARGET_DIR}/output/block_test_libpng_30/log.txt", "--cores", "29", "--asan-cores", "29", "--port", "1366", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "30", "--ratio_start", "0", "--use_blocks", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.block_test_libpng_40]
linux_alias = "block_test_libpng_40_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.block_test_libpng_40_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-31"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/block_test_libpng_40/", "--log", "${TARGET_DIR}/output/block_test_libpng_40/log.txt", "--cores", "30", "--asan-cores", "30", "--port", "1367", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "40", "--ratio_start", "0", "--use_blocks", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.block_test_libpng_50]
linux_alias = "block_test_libpng_50_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.block_test_libpng_50_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-32"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/block_test_libpng_50/", "--log", "${TARGET_DIR}/output/block_test_libpng_50/log.txt", "--cores", "31", "--asan-cores", "31", "--port", "1368", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "50", "--ratio_start", "0", "--use_blocks", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.block_test_libpng_60]
linux_alias = "block_test_libpng_60_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.block_test_libpng_60_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-33"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/block_test_libpng_60/", "--log", "${TARGET_DIR}/output/block_test_libpng_60/log.txt", "--cores", "32", "--asan-cores", "32", "--port", "1369", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "60", "--ratio_start", "0", "--use_blocks", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.block_test_libpng_70]
linux_alias = "block_test_libpng_70_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.block_test_libpng_70_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-34"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/block_test_libpng_70/", "--log", "${TARGET_DIR}/output/block_test_libpng_70/log.txt", "--cores", "33", "--asan-cores", "33", "--port", "1370", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "70", "--ratio_start", "0", "--use_blocks", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.block_test_libpng_80]
linux_alias = "block_test_libpng_80_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.block_test_libpng_80_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-35"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/block_test_libpng_80/", "--log", "${TARGET_DIR}/output/block_test_libpng_80/log.txt", "--cores", "34", "--asan-cores", "34", "--port", "1371", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "80", "--ratio_start", "0", "--use_blocks", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.block_test_libpng_90]
linux_alias = "block_test_libpng_90_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.block_test_libpng_90_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-36"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/block_test_libpng_90/", "--log", "${TARGET_DIR}/output/block_test_libpng_90/log.txt", "--cores", "35", "--asan-cores", "35", "--port", "1372", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "90", "--ratio_start", "0", "--use_blocks", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

[tasks.block_test_libpng_100]
linux_alias = "block_test_libpng_100_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.block_test_libpng_100_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-37"
args = ["--input", "./corpus", "--output", "${TARGET_DIR}/output/block_test_libpng_100/", "--log", "${TARGET_DIR}/output/block_test_libpng_100/log.txt", "--cores", "36", "--asan-cores", "36", "--port", "1373", "--iterations", "3000", "--duration", "86400", "--dynamic_sanitizer", "--dynamic_sanitizer_cutoff", "0", "--dynamic_sanitizer_ratio", "100", "--ratio_start", "0", "--use_blocks", "--", "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}"]
dependencies = ["harness", "fuzzer"]

##
##
##
# 24h Campaigns: for each target, 3 campaigns are defined: normal, asan, and dynamic asan
# With 5 targets, this results in 15 campaigns; use a different core for each; also different output/log directories
##
##
##

#LibPNG Campaigns
[tasks.normal_libpng]
linux_alias = "normal_libpng_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.normal_libpng_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-1"
args = [
  "--input",
  "./corpus",
  "--output",
  "${TARGET_DIR}/output/normal_libpng/",
  "--log",
  "${TARGET_DIR}/output/normal_libpng/log.txt",
  "--cores",
  "0",
  "--port",
  "1337",
  "--iterations",
  "3000",
  "--duration",
  "36000",
  "--",
  "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}",
]
dependencies = ["harness", "fuzzer"]

[tasks.asan_libpng]
linux_alias = "asan_libpng_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.asan_libpng_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-2"
args = [
  "--input",
  "./corpus",
  "--output",
  "${TARGET_DIR}/output/asan_libpng/",
  "--log",
  "${TARGET_DIR}/output/asan_libpng/log.txt",
  "--cores",
  "1",
  "--asan-cores",
  "1",
  "--port",
  "1338",
  "--iterations",
  "3000",
  "--duration",
  "7200",
  "--",
  "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}",
]
dependencies = ["harness", "fuzzer"]

[tasks.ad_libpng]
linux_alias = "ad_libpng_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ad_libpng_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-3"
args = [
  "--input",
  "./corpus",
  "--output",
  "${TARGET_DIR}/output/ad_libpng/",
  "--log",
  "${TARGET_DIR}/output/ad_libpng/log.txt",
  "--cores",
  "2",
  "--asan-cores",
  "2",
  "--port",
  "1339",
  "--iterations",
  "1000",
  "--duration",
  "7200", 
  # "--verbose",
  "--dynamic_sanitizer",
  "--dynamic_sanitizer_cutoff",
  "0", # 1e9
  "--dynamic_sanitizer_ratio",
  "30",
  "--ratio_start",
  "50",
  "--",
  "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}",
]
dependencies = ["harness", "fuzzer"]

#LibTIFF Campaigns
[tasks.normal_libtiff]
linux_alias = "normal_libtiff_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.normal_libtiff_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-4"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libtiff/corpus/tiff_read_rgba_fuzzer",
  "--output",
  "${TARGET_DIR}/output/normal_libtiff/",
  "--log",
  "${TARGET_DIR}/output/normal_libtiff/log.txt",
  "--cores",
  "3",
  "--port",
  "1340",
  "--iterations",
  "1000",
  "--duration",
  "36000",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libtiff/artifacts/tiff_read_rgba_fuzzer",
]
dependencies = ["harness", "fuzzer"]

[tasks.asan_libtiff]
linux_alias = "asan_libtiff_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.asan_libtiff_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-5"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libtiff/corpus/tiff_read_rgba_fuzzer",
  "--output",
  "${TARGET_DIR}/output/asan_libtiff/",
  "--log",
  "${TARGET_DIR}/output/asan_libtiff/log.txt",
  "--cores",
  "4",
  "--asan-cores",
  "4",
  "--port",
  "1341",
  "--iterations",
  "2000",
  "--duration",
  "7200",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libtiff/artifacts/tiff_read_rgba_fuzzer",
]
dependencies = ["harness", "fuzzer"]

[tasks.ad_libtiff]
linux_alias = "ad_libtiff_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ad_libtiff_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-6"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libtiff/corpus/tiff_read_rgba_fuzzer",
  "--output",
  "${TARGET_DIR}/output/ad_libtiff/",
  "--log",
  "${TARGET_DIR}/output/ad_libtiff/log.txt",
  "--cores",
  "5",
  "--asan-cores",
  "5",
  "--port",
  "1342",
  "--iterations",
  "2000",
  "--duration",
  "7200", 
  "--dynamic_sanitizer",
  "--dynamic_sanitizer_cutoff",
  "0", # 1e9
  "--dynamic_sanitizer_ratio",
  "30",
  "--ratio_start",
  "50",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libtiff/artifacts/tiff_read_rgba_fuzzer",
]
dependencies = ["harness", "fuzzer"]

#LibJPEG Campaigns
[tasks.normal_libjpeg]
linux_alias = "normal_libjpeg_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.normal_libjpeg_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-7"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/seed-corpora/bugs/compress/16bit",
  "--output",
  "${TARGET_DIR}/output/normal_libjpeg/",
  "--log",
  "${TARGET_DIR}/output/normal_libjpeg/log.txt",
  "--cores",
  "6",
  "--port",
  "1343",
  "--iterations",
  "1000",
  "--verbose",
  "--duration",
  "36000",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/libjpeg-turbo/build/fuzz/compress16_lossless_fuzzer",
]
dependencies = ["harness", "fuzzer"]

[tasks.asan_libjpeg]
linux_alias = "asan_libjpeg_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.asan_libjpeg_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-8"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/seed-corpora/afl-testcases/jpeg_turbo/full/images",
  "--output",
  "${TARGET_DIR}/output/asan_libjpeg/",
  "--log",
  "${TARGET_DIR}/output/asan_libjpeg/log.txt",
  "--cores",
  "7",
  "--asan-cores",
  "7",
  "--port",
  "1344",
  "--iterations",
  "1000",
  "--duration",
  "36000",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/libjpeg-turbo/build/fuzz/compress_fuzzer",
]
dependencies = ["harness", "fuzzer"]

[tasks.ad_libjpeg]
linux_alias = "ad_libjpeg_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.ad_libjpeg_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-9"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/seed-corpora/afl-testcases/jpeg_turbo/full/images",
  "--output",
  "${TARGET_DIR}/output/ad_libjpeg/",
  "--log",
  "${TARGET_DIR}/output/ad_libjpeg/log.txt",
  "--cores",
  "8",
  "--asan-cores",
  "8",
  "--port",
  "1345",
  "--iterations",
  "1000",
  "--duration",
  "36000", 
  "--dynamic_sanitizer",
  "--dynamic_sanitizer_cutoff",
  "0", # 1e9
  "--dynamic_sanitizer_ratio",
  "10",
  "--ratio_start",
  "50",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/libjpeg-turbo/build/fuzz/compress_fuzzer",
]
dependencies = ["harness", "fuzzer"]

##
##
##
# END OF 24h Campaigns
##
##
##


##
##
##
# Long Campaigns
##
##
##
#LibPNG Campaigns long
[tasks.normal_libpng_long]
linux_alias = "normal_libpng_long_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.normal_libpng_long_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-10"
args = [
  "--input",
  "./corpus",
  "--output",
  "${TARGET_DIR}/output/normal_libpng_long/",
  "--log",
  "${TARGET_DIR}/output/normal_libpng_long/log.txt",
  "--cores",
  "9",
  "--port",
  "1346",
  "--iterations",
  "2000",
  "--duration",
  "518400",
  "--",
  "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}",
]
dependencies = ["harness", "fuzzer"]

[tasks.asan_libpng_long]
linux_alias = "asan_libpng_long_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.asan_libpng_long_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-11"
args = [
  "--input",
  "./corpus",
  "--output",
  "${TARGET_DIR}/output/asan_libpng_long/",
  "--log",
  "${TARGET_DIR}/output/asan_libpng_long/log.txt",
  "--cores",
  "10",
  "--asan-cores",
  "10",
  "--port",
  "1347",
  "--iterations",
  "2000",
  "--duration",
  "518400",
  "--",
  "${TARGET_DIR}/libpng-harness-${CARGO_MAKE_PROFILE}",
]
dependencies = ["harness", "fuzzer"]

#LibTIFF Campaigns long
[tasks.normal_libtiff_long]
linux_alias = "normal_libtiff_long_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.normal_libtiff_long_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-12"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libtiff/corpus/tiff_read_rgba_fuzzer",
  "--output",
  "${TARGET_DIR}/output/normal_libtiff_long/",
  "--log",
  "${TARGET_DIR}/output/normal_libtiff_long/log.txt",
  "--cores",
  "11",
  "--port",
  "1348",
  "--iterations",
  "1000",
  "--duration",
  "518400",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libtiff/artifacts/tiff_read_rgba_fuzzer",
]
dependencies = ["harness", "fuzzer"]

[tasks.asan_libtiff_long]
linux_alias = "asan_libtiff_long_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.asan_libtiff_long_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-13"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libtiff/corpus/tiff_read_rgba_fuzzer",
  "--output",
  "${TARGET_DIR}/output/asan_libtiff_long/",
  "--log",
  "${TARGET_DIR}/output/asan_libtiff_long/log.txt",
  "--cores",
  "12",
  "--asan-cores",
  "12",
  "--port",
  "1349",
  "--iterations",
  "1000",
  "--duration",
  "518400",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/magma/targets/libtiff/artifacts/tiff_read_rgba_fuzzer",
]
dependencies = ["harness", "fuzzer"]

#LibJPEG Campaigns long
[tasks.normal_libjpeg_long]
linux_alias = "normal_libjpeg_long_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.normal_libjpeg_long_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-14"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/seed-corpora/afl-testcases/jpeg_turbo/full/images",
  "--output",
  "${TARGET_DIR}/output/normal_libjpeg_long/",
  "--log",
  "${TARGET_DIR}/output/normal_libjpeg_long/log.txt",
  "--cores",
  "13",
  "--port",
  "1350",
  "--iterations",
  "1000",
  "--verbose",
  "--duration",
  "518400",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/libjpeg-turbo/build/fuzz/compress_fuzzer",
]
dependencies = ["harness", "fuzzer"]

[tasks.asan_libjpeg_long]
linux_alias = "asan_libjpeg_long_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.asan_libjpeg_long_unix]
command = "${TARGET_DIR}/${PROFILE_DIR}/qemu_launcher-${CARGO_MAKE_PROFILE}-15"
args = [
  "--input",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/seed-corpora/afl-testcases/jpeg_turbo/full/images",
  "--output",
  "${TARGET_DIR}/output/asan_libjpeg_long/",
  "--log",
  "${TARGET_DIR}/output/asan_libjpeg_long/log.txt",
  "--cores",
  "14",
  "--asan-cores",
  "14",
  "--port",
  "1351",
  "--iterations",
  "1000",
  "--duration",
  "518400",
  "--",
  "${LIBAFL_LOCATION}/LibAFL/fuzzers/binary_only/qemu_launcher/fuzz_targets/libjpeg-turbo/build/fuzz/compress_fuzzer",
]
dependencies = ["harness", "fuzzer"]

##
##
##
# END OF Long Campaigns
##
##
##

[tasks.test]
linux_alias = "test_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.test_unix]
script_runner = "@shell"
script = '''
echo "Profile: ${PROFILE}"
cd injection_test || exit 1
make
mkdir in || true
echo aaaaaaaaaa > in/a
timeout 10s "$(find ${TARGET_DIR} -name 'qemu_launcher')" -o out -i in -j ../injections.toml -v -- ./static >/dev/null 2>fuzz.log || true
if [ -z "$(grep -Ei "found.*injection" fuzz.log)" ]; then
    echo "Fuzzer does not generate any testcases or any crashes"
    echo "Logs:"
    cat fuzz.log
    exit 1
else
    echo "Fuzzer is working"
fi
make clean
#rm -rf in out fuzz.log || true
'''
dependencies = ["build_unix"]

[tasks.clean]
linux_alias = "clean_unix"
mac_alias = "clean_unix"
windows_alias = "unsupported"

[tasks.clean_unix]
# Disable default `clean` definition
clear = true
script_runner = "@shell"
script = '''
rm -rf ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}
cargo clean
'''
